query AllCalendarExhibitions(){
  AllCalendarExhibitions(
    filter: {
      eventType: { eq: "exhibition" }
    },
    orderBy: [dateStart_ASC]
  ) {
    dateStart
    dateEnd
    link
    note
    title
    address
  }
}
