query landing {
  landing {
    banner {
      media {
        ... on VideoRecord {
          id
          file {
            height
            provider
            providerUid
            thumbnailUrl
            title
            url
            width
          }
        }
      }
    }
    dynamicContentBlocks {
      title
      subtext
      bodyText
      anchorpoint
      blockType
      buttons {
        title
        size
        linkType
        url
        anchorpoint
        page {
          ... on PageRecord {
            slug
          }
          ... on PageChildRecord {
            slug
            parentPage {
              slug
            }
          }
        }
      }
      dynamicContent {
        ... on ProjectRecord {
          id
          title
          blurb
          techSpecs
          credits
          url
          media {
            ... on ImageRecord {
              file {
                url
              }
              credits
              caption
            }
            ... on GifRecord {
              credit
              caption
              file {
                url
              }
            }
            ... on VideoRecord {
              file {
                url
                thumbnailUrl
              }
              credits
              caption
            }
          }
        }
        ... on InstagramPostRecord {
              title
              link
              alt
              thumbnail {
                url
                title
                alt
              }
        }
        ... on PageButtonRecord {
          title
          size
          linkType
          url
          anchorpoint
          page {
            ... on PageRecord {
              slug
            }
            ... on PageChildRecord {
              slug
              parentPage {
                slug
              }
            }
          }
        }
      }
    }
  }
  allFeatures {
    title
    description
  }
  allEcosystems {
    title
    description
    link
    image {
      url
      alt
      title
    }
  }
  allFaqs {
    question
    answer
  }
}
