query allProjects {
  allProjects {
    title
    blurb
    techSpecs
    credits
    url
    media {
      ... on ImageRecord {
        file {
          url
        }
        credits
        caption
      }
      ... on VideoRecord {
        credits
        caption
        file {
          url
          thumbnailUrl
        }
      }
      ... on GifRecord {
        credit
        caption
        file {
          url
        }
      }
    }
  }
}
