query allFooterNavigations {
  allFooterNavigations {
    title
    menuItems {
      menuItem {
        ... on MenuItemRecord {
          title
          navType
          value
          internLink {
            ... on PageRecord {
              slug
            }
            ... on PageChildRecord {
              slug
              parentPage {
                slug
              }
            }
          }
          dropdownItems {
            title
            linkType
            value
            internLink {
              ... on PageRecord {
                slug
              }
              ... on PageChildRecord {
                slug
                parentPage {
                  slug
                }
              }
            }
          }
        }
      }
    }
  }
}
