query allContentData {
  landing {
    banner {
      media {
        ... on VideoRecord {
          id
          file {
            height
            provider
            providerUid
            thumbnailUrl
            title
            url
            width
          }
        }
      }
    }
    dynamicContentBlocks {
      title
      subtext
      bodyText
      anchorpoint
      blockType
      buttons {
        title
        size
        linkType
        url
        anchorpoint
        page {
          ... on PageRecord {
            slug
          }
          ... on PageChildRecord {
            slug
            parentPage {
              slug
            }
          }
        }
      }
      dynamicContent {
        ... on ProjectRecord {
          id
          title
          blurb
          techSpecs
          credits
          url
          media {
            ... on ImageRecord {
              file {
                url
              }
              credits
              caption
            }
            ... on GifRecord {
              credit
              caption
              file {
                url
              }
            }
            ... on VideoRecord {
              file {
                url
                thumbnailUrl
              }
              credits
              caption
            }
          }
        }
        ... on InstagramPostRecord {
              title
              link
              alt
              thumbnail {
                url
                title
                alt
              }
        }
        ... on PageButtonRecord {
          title
          size
          linkType
          url
          anchorpoint
          page {
            ... on PageRecord {
              slug
            }
            ... on PageChildRecord {
              slug
              parentPage {
                slug
              }
            }
          }
        }
      }
    }
  }
  allFeatures {
    title
    description
  }
  allEcosystems {
    title
    description
    link
    image {
      url
      alt
      title
    }
  }
  allFaqs {
    question
    answer
  }
  allMainNavigations {
    menuItem {
      title
      navType
      value
      internLink {
        ... on PageRecord {
          slug
        }
        ... on PageChildRecord {
          slug
          parentPage {
            slug
          }
        }
      }
      dropdownItems {
        title
        linkType
        value
        internLink {
          ... on PageRecord {
            slug
          }
          ... on PageChildRecord {
            slug
            parentPage {
              slug
            }
          }
        }
      }
    }
  }
  allFooterNavigations {
    title
    menuItems {
      menuItem {
        ... on MenuItemRecord {
          title
          navType
          value
          internLink {
            ... on PageRecord {
              slug
            }
            ... on PageChildRecord {
              slug
              parentPage {
                slug
              }
            }
          }
          dropdownItems {
            title
            linkType
            value
            internLink {
              ... on PageRecord {
                slug
              }
              ... on PageChildRecord {
                slug
                parentPage {
                  slug
                }
              }
            }
          }
        }
      }
    }
  }
  allPages {
    title
    description
    slug
    dynamicContentBlocks {
      title
      subtext
      bodyText
      anchorpoint
      blockType
      sidebar
      buttons {
        title
        size
        linkType
        url
        anchorpoint
        page {
          ... on PageRecord {
            slug
          }
          ... on PageChildRecord {
            slug
            parentPage {
              slug
            }
          }
        }
      }
      dynamicContent {
        ... on PageButtonRecord {
          title
          size
          linkType
          url
          anchorpoint
          page {
            ... on PageRecord {
              slug
            }
            ... on PageChildRecord {
              slug
              parentPage {
                slug
              }
            }
          }
        }
        ... on ProjectRecord {
          title
          blurb
          techSpecs
          credits
          url
          media {
            ... on ImageRecord {
              file {
                url
              }
              credits
              caption
            }
            ... on VideoRecord {
              credits
              caption
              file {
                url
                thumbnailUrl
              }
            }
            ... on GifRecord {
              credit
              caption
              file {
                url
              }
            }
          }
        }
        ... on InstagramPostRecord {
          title
          link
          alt
          thumbnail {
            url
            title
            alt
          }
        }
      }
    }
  }
  # allPageChildren {
  #     title
  #     description
  #     slug
  #     parentPage {
  #       slug
  #     }
  #     dynamicContentBlocks {
  #       title
  #       subtext
  #       bodyText
  #       anchorpoint
  #       blockType
  #       sidebar
  #       buttons {
  #         title
  #         size
  #         linkType
  #         url
  #         anchorpoint
  #         page {
  #           ... on PageRecord {
  #             slug
  #           }
  #           ... on PageChildRecord {
  #             slug
  #             parentPage {
  #               slug
  #             }
  #           }
  #         }
  #       }
  #       dynamicContent {
  #       ... on PageButtonRecord {
  #         title
  #         size
  #         linkType
  #         url
  #         anchorpoint
  #         page {
  #           ... on PageRecord {
  #             slug
  #           }
  #           ... on PageChildRecord {
  #             slug
  #             parentPage {
  #               slug
  #             }
  #           }
  #         }
  #       }
  #       ... on ProjectRecord {
  #         title
  #         blurb
  #         techSpecs
  #         credits
  #         url
  #         media {
  #           ... on ImageRecord {
  #             file {
  #               url
  #             }
  #             credits
  #             caption
  #           }
  #           ... on VideoRecord {
  #             credits
  #             caption
  #             file {
  #               url
  #               thumbnailUrl
  #             }
  #           }
  #           ... on GifRecord {
  #             credit
  #             caption
  #             file {
  #               url
  #             }
  #           }
  #         }
  #       }
  #       ... on InstagramPostRecord {
  #         title
  #         link
  #         alt
  #         thumbnail {
  #           url
  #           title
  #           alt
  #         }
  #       }
  #     }
  #   }
  # }
  allGuides {
    title
    description
    estimatedTime
    url
    image {
      url
      title
      alt
    }
  }
  allTutorials {
    title
    description
    estimatedTime
    url
    image {
      url
      title
      alt
    }
  }
  # allNews {
  #   title
  #   description
  #   url
  #   image {
  #     url
  #     title
  #     alt
  #   }
  #   category {
  #     title
  #   }
  # }
  # allProjects {
  #   title
  #   blurb
  #   techSpecs
  #   credits
  #   url
  #   media {
  #     ... on ImageRecord {
  #       file {
  #         url
  #       }
  #       credits
  #       caption
  #     }
  #     ... on VideoRecord {
  #       credits
  #       caption
  #       file {
  #         url
  #         thumbnailUrl
  #       }
  #     }
  #     ... on GifRecord {
  #       credit
  #       caption
  #       file {
  #         url
  #       }
  #     }
  #   }
  # }
  # allCalendars {
  #   eventType
  #   dateStart
  #   dateEnd
  #   link
  #   note
  #   title
  #   address
  # }
}
